# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile for the IPTS touchscreen driver
#

obj-$(CONFIG_MISC_IPTS) += ipts.o
ipts-objs := control.o config.o math.o mei.o receiver.o resources.o uapi.o contact.o \
  heatmap.o input_device.o touch-processing.o
